---------------------------------------- TẠO PDB (LƯU Ý: TỰ THAY ĐƯỜNG DẪN) ----------------------------------------
----- CHUYỂN VỀ CDB -----
ALTER SESSION SET CONTAINER=CDB$ROOT;
/*
----- XÓA PDB -----
BEGIN
    EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE "22127197_470_247"
      INCLUDING DATAFILES';
END;
*/
----- TẠO PDB -----
CREATE PLUGGABLE DATABASE "22127197_470_247" ADMIN USER ADMIN_PJ IDENTIFIED BY 123
  FILE_NAME_CONVERT=(
    'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\PDBSEED\SYSTEM01.DBF', 'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\NEW_PDB\SYSTEM01.DBF',
    'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\PDBSEED\SYSAUX01.DBF', 'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\NEW_PDB\SYSAUX01.DBF',
    'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\PDBSEED\UNDOTBS01.DBF', 'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\NEW_PDB\UNDOTBS01.DBF',
    'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\PDBSEED\TEMP012025-02-27_09-03-08-414-AM.DBF', 'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\NEW_PDB\TEMP012025-02-27_09-03-08-414-AM.DBF'
  )
  STORAGE UNLIMITED TEMPFILE REUSE;

----- MỞ PDB NẾU PDB "MOUNTED" -----
 ALTER PLUGGABLE DATABASE "22127197_470_247" OPEN READ WRITE;

---------------------------------------- CẤP QUYỀN CHO TÀI KHOẢN "ADMIN" LÀ ADMIN CỦA PDB ----------------------------------------
----- CHUYỂN SANG PDB -----
ALTER SESSION SET CONTAINER = "22127197_470_247";

----- CẤP QUYỀN -----
GRANT DBA TO ADMIN_PJ;
GRANT EXECUTE ANY PROCEDURE TO ADMIN_PJ;
GRANT DROP USER TO ADMIN_PJ;
GRANT UNLIMITED TABLESPACE TO ADMIN_PJ;
---------------------------------------- TẠO BẢNG ----------------------------------------
----- KẾT NỐI VÀO PDB BẰNG TÀI KHOẢN "ADMIN_PJ" -----
CONN ADMIN_PJ/123@localhost:1521/"22127197_470_247";
/*
-----XÓA BẢNG -----
-- XÓA BẢNG DANGKY (bảng phụ thuộc nhiều FK)
DROP TABLE DANGKY CASCADE CONSTRAINTS;
-- XÓA BẢNG MOMON
DROP TABLE MOMON CASCADE CONSTRAINTS;
-- XÓA BẢNG HOCPHAN
DROP TABLE HOCPHAN CASCADE CONSTRAINTS;
-- XÓA BẢNG SINHVIEN
DROP TABLE SINHVIEN CASCADE CONSTRAINTS;
-- XÓA BẢNG NHANVIEN
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
-- XÓA BẢNG DONVI
DROP TABLE DONVI CASCADE CONSTRAINTS;
*/
----- Tạo bảng ĐƠN VỊ -----
CREATE TABLE DONVI (
    MADV   VARCHAR2(10) PRIMARY KEY,
    TENDV  NVARCHAR2(100) NOT NULL,
    LOAIDV NVARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV  VARCHAR2(10)
);

----- Tạo bảng NHÂN VIÊN -----
CREATE TABLE NHANVIEN (
    MANV   VARCHAR2(10) PRIMARY KEY,
    HOTEN  NVARCHAR2(100) NOT NULL,
    PHAI   NVARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    LUONG  NUMBER(10, 2),
    PHUCAP NUMBER(10, 2),
    DT     VARCHAR2(15),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')),
    MADV   VARCHAR2(10),
    CONSTRAINT FK_NHANVIEN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

----- Ràng buộc TRƯỞNG ĐƠN VỊ phải là 1 nhân viên có trong bảng NHANVIEN -----
ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI_TRGDV FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANV);

----- Tạo bảng SINH VIÊN -----
CREATE TABLE SINHVIEN (
    MASV      VARCHAR2(10) PRIMARY KEY,
    HOTEN     NVARCHAR2(100) NOT NULL,
    PHAI      NVARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH    DATE,
    DCHI      NVARCHAR2(200),
    DT        VARCHAR2(15),
    KHOA      VARCHAR2(10),
    TINHTRANG NVARCHAR2(20),
    CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

----- Tạo bảng HỌC PHẦN -----
CREATE TABLE HOCPHAN (
    MAHP  VARCHAR2(10) PRIMARY KEY,
    TENHP NVARCHAR2(100) NOT NULL,
    SOTC  NUMBER(2),
    STLT  NUMBER(3),
    STTH  NUMBER(3),
    MADV  VARCHAR2(10),
    CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

----- Tạo bảng MỞ MÔN -----
CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK   NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM  NUMBER(4),
    CONSTRAINT FK_MOMON_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    CONSTRAINT FK_MOMON_GV FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

----- Tạo bảng ĐĂNG KÝ -----
CREATE TABLE DANGKY (
    MASV    VARCHAR2(10),
    MAMM    VARCHAR2(10),
    DIEMTH  NUMBER(5, 2),
    DIEMQT  NUMBER(5, 2),
    DIEMCK  NUMBER(5, 2),
    DIEMTK  NUMBER(5, 2),
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV, MAMM),
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_MOMON FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);

-- Thêm dữ liệu cho bảng DONVI (Khoa và Phòng)
INSERT ALL
    INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('HOA', 'Khoa Hóa học', 'Khoa', NULL)
    INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('CNTT', 'Khoa Công nghệ thông tin', 'Khoa', NULL)
    INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PĐT', 'Phòng Đào tạo', 'Phòng', NULL)
    INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PKT', 'Phòng Kế toán', 'Phòng', NULL)
SELECT 1 FROM DUAL;

-- Thêm dữ liệu cho bảng NHANVIEN (Giảng viên và nhân viên hành chính)
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV)
SELECT 
    'NV' || LPAD(LEVEL, 4, '0'),
    'Nhân viên ' || LEVEL,
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 'Nam' ELSE 'Nữ' END,
    TO_DATE('1970-01-01', 'YYYY-MM-DD') + MOD(LEVEL, 18250),
    10000000 + (MOD(LEVEL, 5000) * 1000),
    1000000 + (MOD(LEVEL, 500) * 500),
    '091' || LPAD(LEVEL, 7, '0'),
    CASE 
        WHEN LEVEL <= 500 THEN 'NVCB'
        WHEN LEVEL <= 700 THEN 'GV'
        WHEN LEVEL <= 720 THEN 'NV PĐT'
        WHEN LEVEL <= 730 THEN 'NV PKT'
        WHEN LEVEL <= 745 THEN 'NV TCHC'
        WHEN LEVEL <= 755 THEN 'NV CTSV'
        ELSE 'TRGĐV'
    END,
    CASE 
        WHEN LEVEL <= 700 THEN 'HOA'
        WHEN LEVEL <= 720 THEN 'PĐT'
        WHEN LEVEL <= 730 THEN 'PKT'
        WHEN LEVEL <= 745 THEN 'CNTT'
        ELSE 'PĐT'
    END
FROM DUAL
CONNECT BY LEVEL <= 770;

-- Cập nhật TRGDV cho các đơn vị
UPDATE DONVI SET TRGDV = 'NV0701' WHERE MADV = 'HOA';
UPDATE DONVI SET TRGDV = 'NV0756' WHERE MADV = 'CNTT';
UPDATE DONVI SET TRGDV = 'NV0721' WHERE MADV = 'PĐT';
UPDATE DONVI SET TRGDV = 'NV0731' WHERE MADV = 'PKT';

UPDATE NHANVIEN SET VAITRO = 'TRGĐV' WHERE MANV = 'NV0701';
UPDATE NHANVIEN SET VAITRO = 'TRGĐV' WHERE MANV = 'NV0756';
UPDATE NHANVIEN SET VAITRO = 'TRGĐV' WHERE MANV = 'NV0721';
UPDATE NHANVIEN SET VAITRO = 'TRGĐV' WHERE MANV = 'NV0731';

-- Thêm dữ liệu cho bảng SINHVIEN
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG)
SELECT 
    'SV' || LPAD(LEVEL, 4, '0'), 
    'Sinh viên ' || LEVEL, 
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 'Nam' ELSE 'Nữ' END, 
    TO_DATE('2000-01-01', 'YYYY-MM-DD') + MOD(LEVEL, 3650),
    'Địa chỉ ' || LEVEL,
    '090' || LPAD(LEVEL, 7, '0'),
    CASE WHEN MOD(LEVEL, 3) = 0 THEN 'HOA' WHEN MOD(LEVEL, 3) = 1 THEN 'CNTT' ELSE NULL END, 
    CASE MOD(LEVEL, 3) WHEN 0 THEN 'Đang học' WHEN 1 THEN 'Bảo lưu' ELSE 'Nghỉ học' END
FROM DUAL
CONNECT BY LEVEL <= 4000;

-- Thêm dữ liệu cho bảng HOCPHAN
INSERT INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, MADV)
SELECT 
    'HP' || LPAD(LEVEL, 4, '0'),
    'Học phần ' || LEVEL,
    MOD(LEVEL, 4) + 2,
    MOD(LEVEL, 2) + 1,
    MOD(LEVEL, 2) + 1,
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 'HOA' ELSE 'CNTT' END
FROM DUAL
CONNECT BY LEVEL <= 50;

-- Thêm dữ liệu cho bảng MOMON
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM)
SELECT 
    'MM' || LPAD(LEVEL, 4, '0'),
    'HP' || LPAD(MOD(LEVEL, 50) + 1, 4, '0'),
    'NV' || LPAD(500 + MOD(LEVEL, 200), 4, '0'),
    MOD(LEVEL, 3) + 1,
    2023 - MOD(LEVEL, 5)
FROM DUAL
CONNECT BY LEVEL <= 100;

-- Thêm dữ liệu cho bảng DANGKY
INSERT INTO DANGKY (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK)
SELECT 
    'SV' || LPAD(CEIL(LEVEL / 2), 4, '0'),  -- Mỗi SV đăng ký tối đa 2 môn
    'MM' || LPAD(MOD(LEVEL, 100) + 1, 4, '0'),  -- Giữ cho MAMM phân bổ hợp lý
    ROUND(DBMS_RANDOM.VALUE(4, 10), 2),  -- Điểm thành phần
    ROUND(DBMS_RANDOM.VALUE(4, 10), 2),
    ROUND(DBMS_RANDOM.VALUE(4, 10), 2),
    ROUND((ROUND(DBMS_RANDOM.VALUE(4, 10), 2) * 0.3 + 
           ROUND(DBMS_RANDOM.VALUE(4, 10), 2) * 0.3 + 
           ROUND(DBMS_RANDOM.VALUE(4, 10), 2) * 0.4), 2)  -- Điểm tổng kết
FROM DUAL
CONNECT BY LEVEL <= 8000;

-- Xem data đã nhập 
SELECT * FROM ADMIN_PJ.NHANVIEN;
SELECT * FROM ADMIN_PJ.DONVI;
SELECT * FROM ADMIN_PJ.SINHVIEN;
SELECT * FROM ADMIN_PJ.HOCPHAN;
SELECT * FROM ADMIN_PJ.MOMON;
SELECT * FROM ADMIN_PJ.DANGKY;

CONN ADMIN_PJ/123@localhost:1521/"22127197_470_247";
-- Tạo user
BEGIN
    FOR rec IN (SELECT MANV FROM NHANVIEN) LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || rec.MANV || 
                          ' IDENTIFIED BY "NV' || rec.MANV || '@123"';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || rec.MANV;
    END LOOP;
    
    FOR rec IN (SELECT MASV FROM SINHVIEN) LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || rec.MASV || 
                          ' IDENTIFIED BY "SV' || rec.MASV || '@123"';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || rec.MASV;
    END LOOP;
END;
/

CONN ADMIN_PJ/123@localhost:1521/"22127197_470_247";
-- Xem user
SELECT USERNAME, ACCOUNT_STATUS 
FROM DBA_USERS 
WHERE USERNAME LIKE 'NV%'--'SV%'
ORDER BY USERNAME;


